trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs:
    - job: Build1
      strategy:
        matrix:
          node12:
            NodeVersion: 12
          node14:
            NodeVersion: 14
      steps:
        - script: npm install
        - script: npm run coverage
        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testRunner: JUnit
            testResultsFiles: 'junit/*.xml'
        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: coverage/*.xml
            reportDirectory: coverage
  - stage: Publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
    - job: Publish1
      steps:
      - script: |
          echo Try Publish Here
