on: push
name: CI
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Test
      run: npm run coverage
    - name: Version Check
      id: version-check
      run: |
        set +e
        PackageName=$(jq -r .name < package.json)
        NewPackageVersion=$(jq -r .version < package.json)
        npm show $PackageName versions | grep -q "'${NewPackageVersion}'"
        VersionAlreadyPublished=$?
        if [ $VersionAlreadyPublished -eq 1 ]; then
          echo "::set-output name=PUBLISH::true"
        else
          echo "::set-output name=PUBLISH::false"
        fi
    - name: Publish
      if: github.ref == 'refs/heads/main' && steps.version-check.outputs.PUBLISH == 'true'
      run: npm publish
      env:
        NPM_CUSTOM_NPMRC: ${{secrets.NPMRC}}
